version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/pythonx/clap/fuzzymatch-rs"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
